import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import Providers from '@/app/providers';
import '@/styles/globals.css';
import { fontEpilogueVariable } from '@/styles/fonts';

import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

import { routing } from '@/i18n/routing';
import { Locale } from '@/i18n/types';
import { cn } from '@/lib/cn';
import { RootLayoutProps } from './types';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body className={cn(fontEpilogueVariable, 'antialiased font-epilogue')}>
          <Providers>{children}</Providers>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
